
version: '3.9'

services:

  my_app:

    build:

      context: .
      dockerfile: Dockerfile02

    expose:
      - '7878'

    deploy:
      replicas: 4 
    
    restart: always

    environment:
      - PING_LISTEN_PORT=7878

    networks:
      - front-network


  reverse-proxy:

    image: nginx:latest

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    
    ports:
      - 8080:80

    depends_on: 
      - my_app
    
    networks:
      - front-network


networks:
  
  front-network:
    driver: bridge


volumes:
  db_data: